version: '3.7'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=dockerCarier-app
            - POSTGRES_DB=carrierApp
        expose:
            - 5433
        ports:
            - "5435:5433"
    django:
        build: ./backend
        command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
        volumes:
            - ./backend/:/app/backend
        ports:
            - "8000:8000"
        depends_on:
            - db
    frontend:
        build: ./frontend
        command: ["npm", "start"]
        volumes:
            - ./frontend/:/app/frontend
            - ./frontend/node_modules:/app/frontend/node_modules
        ports:
            - "3000:3000"

volumes:
    node-modules:
