# Generated by Django 2.2.6 on 2019-11-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False, verbose_name='collection id')),
                ('collection_name', models.CharField(max_length=200, verbose_name='collection name')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False, verbose_name='request id')),
                ('request_method', models.CharField(max_length=50, verbose_name='request method')),
                ('request_url', models.CharField(max_length=200, verbose_name='request url')),
                ('request_headers', models.TextField(verbose_name='request headers')),
                ('request_body', models.TextField(verbose_name='request headers')),
                ('request_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('env_id', models.AutoField(primary_key=True, serialize=False, verbose_name='environment id')),
                ('env_name', models.CharField(max_length=200, verbose_name='environment name')),
                ('env_url', models.CharField(max_length=200, verbose_name='environment url')),
                ('env_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Collection')),
            ],
        ),
    ]
