# Generated by Django 2.2.6 on 2019-10-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=50, verbose_name='request method')),
                ('request_url', models.CharField(max_length=200, verbose_name='request url')),
                ('request_headers', models.TextField(verbose_name='request headers')),
                ('request_body', models.TextField(verbose_name='request headers')),
                ('request_time', models.DateField()),
            ],
        ),
    ]
